apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-db-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abd-elrahman-mohamed-anter/k8s-db-prometheus-grafana-local.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
